// Generated by CoffeeScript 1.6.3
$(function() {
  var files1, num, progressMonitor, refocus1;
  files1 = (function() {
    var _i, _len, _ref, _results;
    _ref = range(0, 39, 1);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      num = _ref[_i];
      _results.push("img/f_" + num + ".jpg");
    }
    return _results;
  })();
  refocus1 = refocus(files1, "#container1");
  progressMonitor = setInterval((function() {
    var num_loaded, num_total;
    num_loaded = refocus1.numImgLoaded();
    num_total = refocus1.numImgTotal();
    $("#progress").val(num_loaded / num_total * 100);
    if (num_loaded === num_total) {
      $("#go").click(function() {
        return $("#info-mode").css("z-index", "0");
      });
      return $("#go").removeAttr('disabled');
    }
  }), 100);
  $('#selector input').change(function() {
    if ($(this).val() === 'Peripheral') {
      return $('#container1').css('z-index', 2);
    } else {
      return $('#container1').css('z-index', 0);
    }
  });
  return $("#info-link").click(function() {
    return $("#info-mode").css("z-index", "2");
  });
});
